name: C/C++ CI

on:
  push:
    branches: [ "branchAutomake" ]
  pull_request:
    branches: [ "branchAutomake" ]
  workflow_dispatch:
    branches: [ "branchAutomake" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: Build tarball distribution file
      run: make dist
    - name: Upload tarball distribution file
      uses: actions/upload-artifact@v4.4.3
      with: 
      name: tarball
      path: "*.tar.gz"
    # Artifact name
