name: C/C++ CI

on:
  push:
    branches: [ "branchAutoMake" ]
  pull_request:
    branches: [ "branchAutoMake" ]
  workflow_dispatch:
    branch: [ "branchAutoMake" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: ./configure
    - name: make
      run: make
      name: Build tarball distribution file
      run: make dist
