name: C/C++ CI

on:
  push:
    branches: [ "branchHTTPserver" ]
  pull_request:
    branches: [ "branchHTTPserver" ]
  workflow_dispatch:
    branches: [ "branchHTTPserver" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: QEMU instalation
      uses: docker/setup-qemu-action@v3
      
    - name: Docker Buildx installation
      uses: docker/setup-buildx-action@v1

    - name: build ls
      run: docker buildx ls

    - name: Log in to dockerhub
      run: docker login -u ${{ vars.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}    

    - name: Build Dockerfile image
      run: docker build --platform=linux/amd64 -t reshet08/lr4_calculation:amd64 --push
    - name: configure
      run: ./configure
    
    - name: make
      run: make
   
    - name: autotest
      run: cd ./tests && make check
