name: C/C++ CI

on:
  push:
    branches: [ "branchAutoPackage" ]
  pull_request:
    branches: [ "branchAutoPackage" ]
  workflow_dispatch:
    branches: [ "branchAutoPackage" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: Build deb package
      run: sudo rm -r deb && sudo make deb && dpkg-deb --build deb
    - name: Upload deb package
      uses: actions/upload-artifact@v4.4.3
      with: 
        name: deb
        path: "*.deb"
